### ISSUE TITLE
Papirus Dark not working, loads default iconset.

### ISSUE THREAD

**Issue by Samillion** [PapirusDevelopmentTeam/papirus-smplayer-theme#1]
**System:**
Debian Stretch (Testing)
Gnome 3.22
SMPlayer 16.4 (Debian Packages)
Arc Theme
Papirus Icon Theme

**The Issue:**
I've installed the themes for SMPlayer by moving the Papirus and Papirus-Dark folders (the ones with the rcc files, not the ones from src)  to /usr/share/smplayer/themes/

The non-dark version works really well, everything loads up perfectly. However, Papirus Dark seems to be loading the default iconset, as shown in the screenshot.

Papirus working just fine:

![screenshot from 2016-10-06 04-50-59](https://cloud.githubusercontent.com/assets/17427046/19138936/17b19ee6-8b89-11e6-9033-0deb66ca7beb.png)

Papirus-Dark not working, loads default iconset:

![screenshot from 2016-10-06 04-52-27](https://cloud.githubusercontent.com/assets/17427046/19138944/27f5ddbc-8b89-11e6-9c13-3bd402075c61.png)

Any help on this would be much appreciated.

**Comment by Samillion** [comment]
**Solved:**
Right after I submitted this ticket, I noticed that none of the pre-installed themes had a hyphen or any symbol.

Rename the Papirus-Dark folder to PapirusDark, as in remove the hyphen. Seems that SMPlayer has trouble with it.

![screenshot from 2016-10-06 05-01-46](https://cloud.githubusercontent.com/assets/17427046/19139098/668a65ba-8b8a-11e6-82bc-524f52926e7a.png)

**Comment by Samillion** [comment]
Re-opened, just to make sure you guys get notified of this issue. Thanks for a wonderful theme and icons.

**Comment by SmartFinn** [comment]
@TrendaFet Thanks!
