### ISSUE TITLE
cp: '/tmp/.../': no such file or directory

### ISSUE THREAD

**Issue by ghost** [PapirusDevelopmentTeam/papirus-smplayer-theme#5]
Hi there.
When I tried to install the papirus-smplayer-theme I got an error that I think it comes from source code not my device.
[Here](https://paste.fedoraproject.org/paste/PjkWRQWD6sMTH0WVtH86MA) is output of installer script:
OS: Fedora 27 x86_64
SMPlayer version: 17.11.2
Tell if you need more details about it. :)
Good luck.

**Comment by arjunv** [comment]
Met with the same error. Output of the installer script, that the above deleted user linked, is no longer available. [Attaching mine.](https://gist.github.com/arjunv/8850ef1889707b7dafc2ca603e736639)

OS: [info.txt](https://gist.github.com/arjunv/47ac1511106ff22c64e93308406e0a74)
SMPlayer Version: 18.3.0-1

**Comment by gersonsosa** [comment]
I made a change in the installation script to fix this issue [PR link](https://github.com/PapirusDevelopmentTeam/papirus-smplayer-theme/pull/6)
