### ISSUE TITLE
Interface SMPlayer

### ISSUE THREAD

**Issue by tiagovla** [PapirusDevelopmentTeam/papirus-smplayer-theme#7]
I installed the theme and changed the icon option in the interface menu. But it doesn't seem to work. Should I do anything else? Thanks!

![screenshot from 2018-06-24 03-21-59](https://user-images.githubusercontent.com/30515389/41816521-c62f1522-775d-11e8-94d4-872a115e4fcb.png)

**Comment by SmartFinn** [comment]
If someone has the same issue just press <kbd>Apply</kbd> and restart SMPlayer.
