### ISSUE TITLE
The interface remains light when a dark theme is applied

### ISSUE THREAD

**Issue by VanHacking** [PapirusDevelopmentTeam/papirus-smplayer-theme#9]
I tried many times but the issue seems to be more than a bad setting. The icons are properly set, dark icons are loaded for light themes and light icons are loader for dark themes, which is correct. However, whenever i set a light or dark Papirus theme, the color scheme remains light, leaving the dark themes unusable. None of the dark Papirus themes works properly, i installed the git version.
As smplayer themes are apparently not in "clear" code, i don't know what to do to correct this issue.

Best regards,
Robin.

![image](https://user-images.githubusercontent.com/51612294/59185111-eb7d5100-8b6f-11e9-9869-77b9b9e8cc35.png)

**Comment by SmartFinn** [comment]
The project provided icons only. The color scheme shouldn't change when you switching Icon set. Install any dark GTK/KDE theme to your system and then use `qt5ct` command to change the theme for Qt apps.
